[build]
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

# Define environment variables
[variables]
PORT = "8080" 